server:
  port: 8091
spring:
  profiles:
    active: dev
  application:
    name: test
  cloud:
    nacos:
       discovery:
          server-addr: localhost:8848
          register-enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true
  metrics:
    web:
      server:
        auto-time-requests: true
logging:
  level:
    root: DEBUG